export const POSITIONS_LIST = [
  {
    value: "left",
    label: "Left",
  },
  {
    value: "right",
    label: "Right",
  },
];

export const COUNTRIES_LIST = [
  { abbreviation: "", label: "Select", phoneCode: "+0" },
  { abbreviation: "AF", label: "Afghanistan", phoneCode: "+93" },
  { abbreviation: "AX", label: "land Islands", phoneCode: "+358" },
  { abbreviation: "AL", label: "Albania", phoneCode: "+355" },
  { abbreviation: "DZ", label: "Algeria", phoneCode: "+213" },
  { abbreviation: "AS", label: "American Samoa", phoneCode: "+1-684" },
  { abbreviation: "AD", label: "Andorra", phoneCode: "+376" },
  { abbreviation: "AO", label: "Angola", phoneCode: "+244" },
  { abbreviation: "AI", label: "Anguilla", phoneCode: "+1-264" },
  { abbreviation: "AQ", label: "Antarctica", phoneCode: "" },
  { abbreviation: "AG", label: "Antigua and Barbuda", phoneCode: "+1-268" },
  { abbreviation: "AR", label: "Argentina", phoneCode: "+54" },
  { abbreviation: "AM", label: "Armenia", phoneCode: "+374" },
  { abbreviation: "AW", label: "Aruba", phoneCode: "+297" },
  { abbreviation: "AU", label: "Australia", phoneCode: "+61" },
  { abbreviation: "AT", label: "Austria", phoneCode: "+43" },
  { abbreviation: "AZ", label: "Azerbaijan", phoneCode: "+994" },
  { abbreviation: "BS", label: "Bahamas", phoneCode: "+1-242" },
  { abbreviation: "BH", label: "Bahrain", phoneCode: "+973" },
  { abbreviation: "BD", label: "Bangladesh", phoneCode: "+880" },
  { abbreviation: "BB", label: "Barbados", phoneCode: "+1-246" },
  { abbreviation: "BY", label: "Belarus", phoneCode: "+375" },
  { abbreviation: "BE", label: "Belgium", phoneCode: "+32" },
  { abbreviation: "BZ", label: "Belize", phoneCode: "+501" },
  { abbreviation: "BJ", label: "Benin", phoneCode: "+229" },
  { abbreviation: "BM", label: "Bermuda", phoneCode: "+1-441" },
  { abbreviation: "BT", label: "Bhutan", phoneCode: "+975" },
  { abbreviation: "BO", label: "Bolivia", phoneCode: "+591" },
  { abbreviation: "BA", label: "Bosnia and Herzegovina", phoneCode: "+387" },
  { abbreviation: "BW", label: "Botswana", phoneCode: "+267" },
  { abbreviation: "BV", label: "Bouvet Island", phoneCode: "" },
  { abbreviation: "BR", label: "Brazil", phoneCode: "+55" },
  {
    abbreviation: "IO",
    label: "British Indian Ocean Territory",
    phoneCode: "+246",
  },
  { abbreviation: "BN", label: "Brunei Darussalam", phoneCode: "+673" },
  { abbreviation: "BG", label: "Bulgaria", phoneCode: "+359" },
  { abbreviation: "BF", label: "Burkina Faso", phoneCode: "+226" },
  { abbreviation: "BI", label: "Burundi", phoneCode: "+257" },
  { abbreviation: "KH", label: "Cambodia", phoneCode: "+855" },
  { abbreviation: "CM", label: "Cameroon", phoneCode: "+237" },
  { abbreviation: "CA", label: "Canada", phoneCode: "+1" },
  { abbreviation: "CV", label: "Cape Verde", phoneCode: "+238" },
  { abbreviation: "KY", label: "Cayman Islands", phoneCode: "+1-345" },
  { abbreviation: "CF", label: "Central African Republic", phoneCode: "+236" },
  { abbreviation: "TD", label: "Chad", phoneCode: "+235" },
  { abbreviation: "CL", label: "Chile", phoneCode: "+56" },
  { abbreviation: "CN", label: "China", phoneCode: "+86" },
  { abbreviation: "CX", label: "Christmas Island", phoneCode: "+61" },
  { abbreviation: "CC", label: "Cocos (Keeling) Islands", phoneCode: "+61" },
  { abbreviation: "CO", label: "Colombia", phoneCode: "+57" },
  { abbreviation: "KM", label: "Comoros", phoneCode: "+269" },
  { abbreviation: "CG", label: "Congo", phoneCode: "+242" },
  {
    abbreviation: "CD",
    label: "Congo, The Democratic Republic of the",
    phoneCode: "+243",
  },
  { abbreviation: "CK", label: "Cook Islands", phoneCode: "+682" },
  { abbreviation: "CR", label: "Costa Rica", phoneCode: "+506" },
  { abbreviation: "CI", label: "Cote D'Ivoire", phoneCode: "+225" },
  { abbreviation: "HR", label: "Croatia", phoneCode: "+385" },
  { abbreviation: "CU", label: "Cuba", phoneCode: "+53" },
  { abbreviation: "CY", label: "Cyprus", phoneCode: "+357" },
  { abbreviation: "CZ", label: "Czech Republic", phoneCode: "+420" },
  { abbreviation: "DK", label: "Denmark", phoneCode: "+45" },
  { abbreviation: "DJ", label: "Djibouti", phoneCode: "+253" },
  { abbreviation: "DM", label: "Dominica", phoneCode: "+1-767" },
  {
    abbreviation: "DO",
    label: "Dominican Republic",
    phoneCode: "+1-809, +1-829, +1-849",
  },
  { abbreviation: "EC", label: "Ecuador", phoneCode: "+593" },
  { abbreviation: "EG", label: "Egypt", phoneCode: "+20" },
  { abbreviation: "SV", label: "El Salvador", phoneCode: "+503" },
  { abbreviation: "GQ", label: "Equatorial Guinea", phoneCode: "+240" },
  { abbreviation: "ER", label: "Eritrea", phoneCode: "+291" },
  { abbreviation: "EE", label: "Estonia", phoneCode: "+372" },
  { abbreviation: "ET", label: "Ethiopia", phoneCode: "+251" },
  {
    abbreviation: "FK",
    label: "Falkland Islands (Malvinas)",
    phoneCode: "+500",
  },
  { abbreviation: "FO", label: "Faroe Islands", phoneCode: "+298" },
  { abbreviation: "FJ", label: "Fiji", phoneCode: "+679" },
  { abbreviation: "FI", label: "Finland", phoneCode: "+358" },
  { abbreviation: "FR", label: "France", phoneCode: "+33" },
  { abbreviation: "GF", label: "French Guiana", phoneCode: "+594" },
  { abbreviation: "PF", label: "French Polynesia", phoneCode: "+689" },
  { abbreviation: "TF", label: "French Southern Territories", phoneCode: "" },
  { abbreviation: "GA", label: "Gabon", phoneCode: "+241" },
  { abbreviation: "GM", label: "Gambia", phoneCode: "+220" },
  { abbreviation: "GE", label: "Georgia", phoneCode: "+995" },
  { abbreviation: "DE", label: "Germany", phoneCode: "+49" },
  { abbreviation: "GH", label: "Ghana", phoneCode: "+233" },
  { abbreviation: "GI", label: "Gibraltar", phoneCode: "+350" },
  { abbreviation: "GR", label: "Greece", phoneCode: "+30" },
  { abbreviation: "GL", label: "Greenland", phoneCode: "+299" },
  { abbreviation: "GD", label: "Grenada", phoneCode: "+1-473" },
  { abbreviation: "GP", label: "Guadeloupe", phoneCode: "+590" },
  { abbreviation: "GU", label: "Guam", phoneCode: "+1-671" },
  { abbreviation: "GT", label: "Guatemala", phoneCode: "+502" },
  { abbreviation: "GG", label: "Guernsey", phoneCode: "+44-1481" },
  { abbreviation: "GN", label: "Guinea", phoneCode: "+224" },
  { abbreviation: "GW", label: "Guinea-Bissau", phoneCode: "+245" },
  { abbreviation: "GY", label: "Guyana", phoneCode: "+592" },
  { abbreviation: "HT", label: "Haiti", phoneCode: "+509" },
  {
    abbreviation: "HM",
    label: "Heard Island and Mcdonald Islands",
    phoneCode: "",
  },
  {
    abbreviation: "VA",
    label: "Holy See (Vatican City State)",
    phoneCode: "+379",
  },
  { abbreviation: "HN", label: "Honduras", phoneCode: "+504" },
  { abbreviation: "HK", label: "Hong Kong", phoneCode: "+852" },
  { abbreviation: "HU", label: "Hungary", phoneCode: "+36" },
  { abbreviation: "IS", label: "Iceland", phoneCode: "+354" },
  { abbreviation: "IN", label: "India", phoneCode: "+91" },
  { abbreviation: "ID", label: "Indonesia", phoneCode: "+62" },
  { abbreviation: "IR", label: "Iran, Islamic Republic of", phoneCode: "+98" },
  { abbreviation: "IQ", label: "Iraq", phoneCode: "+964" },
  { abbreviation: "IE", label: "Ireland", phoneCode: "+353" },
  { abbreviation: "IM", label: "Isle of Man", phoneCode: "+44-1624" },
  { abbreviation: "IL", label: "Israel", phoneCode: "+972" },
  { abbreviation: "IT", label: "Italy", phoneCode: "+39" },
  { abbreviation: "JM", label: "Jamaica", phoneCode: "+1-876" },
  { abbreviation: "JP", label: "Japan", phoneCode: "+81" },
  { abbreviation: "JE", label: "Jersey", phoneCode: "+44-1534" },
  { abbreviation: "JO", label: "Jordan", phoneCode: "+962" },
  { abbreviation: "KZ", label: "Kazakhstan", phoneCode: "+7" },
  { abbreviation: "KE", label: "Kenya", phoneCode: "+254" },
  { abbreviation: "KI", label: "Kiribati", phoneCode: "+686" },
  {
    abbreviation: "KP",
    label: "Korea, Democratic People's Republic of",
    phoneCode: "+850",
  },
  { abbreviation: "KR", label: "Korea, Republic of", phoneCode: "+82" },
  { abbreviation: "KW", label: "Kuwait", phoneCode: "+965" },
  { abbreviation: "KG", label: "Kyrgyzstan", phoneCode: "+996" },
  {
    abbreviation: "LA",
    label: "Lao People's Democratic Republic",
    phoneCode: "+856",
  },
  { abbreviation: "LV", label: "Latvia", phoneCode: "+371" },
  { abbreviation: "LB", label: "Lebanon", phoneCode: "+961" },
  { abbreviation: "LS", label: "Lesotho", phoneCode: "+266" },
  { abbreviation: "LR", label: "Liberia", phoneCode: "+231" },
  { abbreviation: "LY", label: "Libyan Arab Jamahiriya", phoneCode: "+218" },
  { abbreviation: "LI", label: "Liechtenstein", phoneCode: "+423" },
  { abbreviation: "LT", label: "Lithuania", phoneCode: "+370" },
  { abbreviation: "LU", label: "Luxembourg", phoneCode: "+352" },
  { abbreviation: "MO", label: "Macao", phoneCode: "+853" },
  {
    abbreviation: "MK",
    label: "Macedonia, The Former Yugoslav Republic of",
    phoneCode: "+389",
  },
  { abbreviation: "MG", label: "Madagascar", phoneCode: "+261" },
  { abbreviation: "MW", label: "Malawi", phoneCode: "+265" },
  { abbreviation: "MY", label: "Malaysia", phoneCode: "+60" },
  { abbreviation: "MV", label: "Maldives", phoneCode: "+960" },
  { abbreviation: "ML", label: "Mali", phoneCode: "+223" },
  { abbreviation: "MT", label: "Malta", phoneCode: "+356" },
  { abbreviation: "MH", label: "Marshall Islands", phoneCode: "+692" },
  { abbreviation: "MQ", label: "Martinique", phoneCode: "+596" },
  { abbreviation: "MR", label: "Mauritania", phoneCode: "+222" },
  { abbreviation: "MU", label: "Mauritius", phoneCode: "+230" },
  { abbreviation: "YT", label: "Mayotte", phoneCode: "+262" },
  { abbreviation: "MX", label: "Mexico", phoneCode: "+52" },
  {
    abbreviation: "FM",
    label: "Micronesia, Federated States of",
    phoneCode: "+691",
  },
  { abbreviation: "MD", label: "Moldova, Republic of", phoneCode: "+373" },
  { abbreviation: "MC", label: "Monaco", phoneCode: "+377" },
  { abbreviation: "MN", label: "Mongolia", phoneCode: "+976" },
  { abbreviation: "ME", label: "Montenegro", phoneCode: "+382" },
  { abbreviation: "MS", label: "Montserrat", phoneCode: "+1-664" },
  { abbreviation: "MA", label: "Morocco", phoneCode: "+212" },
  { abbreviation: "MZ", label: "Mozambique", phoneCode: "+258" },
  { abbreviation: "MM", label: "Myanmar", phoneCode: "+95" },
  { abbreviation: "NA", label: "Namibia", phoneCode: "+264" },
  { abbreviation: "NR", label: "Nauru", phoneCode: "+674" },
  { abbreviation: "NP", label: "Nepal", phoneCode: "+977" },
  { abbreviation: "NL", label: "Netherlands", phoneCode: "+31" },
  { abbreviation: "AN", label: "Netherlands Antilles", phoneCode: "" },
  { abbreviation: "NC", label: "New Caledonia", phoneCode: "+687" },
  { abbreviation: "NZ", label: "New Zealand", phoneCode: "+64" },
  { abbreviation: "NI", label: "Nicaragua", phoneCode: "+505" },
  { abbreviation: "NE", label: "Niger", phoneCode: "+227" },
  { abbreviation: "NG", label: "Nigeria", phoneCode: "+234" },
  { abbreviation: "NU", label: "Niue", phoneCode: "+683" },
  { abbreviation: "NF", label: "Norfolk Island", phoneCode: "+672" },
  {
    abbreviation: "MP",
    label: "Northern Mariana Islands",
    phoneCode: "+1-670",
  },
  { abbreviation: "NO", label: "Norway", phoneCode: "+47" },
  { abbreviation: "OM", label: "Oman", phoneCode: "+968" },
  { abbreviation: "PK", label: "Pakistan", phoneCode: "+92" },
  { abbreviation: "PW", label: "Palau", phoneCode: "+680" },
  {
    abbreviation: "PS",
    label: "Palestinian Territory, Occupied",
    phoneCode: "+970",
  },
  { abbreviation: "PA", label: "Panama", phoneCode: "+507" },
  { abbreviation: "PG", label: "Papua New Guinea", phoneCode: "+675" },
  { abbreviation: "PY", label: "Paraguay", phoneCode: "+595" },
  { abbreviation: "PE", label: "Peru", phoneCode: "+51" },
  { abbreviation: "PH", label: "Philippines", phoneCode: "+63" },
  { abbreviation: "PN", label: "Pitcairn", phoneCode: "+872" },
  { abbreviation: "PL", label: "Poland", phoneCode: "+48" },
  { abbreviation: "PT", label: "Portugal", phoneCode: "+351" },
  { abbreviation: "PR", label: "Puerto Rico", phoneCode: "+1" },
  { abbreviation: "QA", label: "Qatar", phoneCode: "+974" },
  { abbreviation: "RE", label: "Reunion", phoneCode: "+262" },
  { abbreviation: "RO", label: "Romania", phoneCode: "+40" },
  { abbreviation: "RU", label: "Russian Federation", phoneCode: "+7" },
  { abbreviation: "RW", label: "Rwanda", phoneCode: "+250" },
  { abbreviation: "SH", label: "Saint Helena", phoneCode: "+290" },
  { abbreviation: "KN", label: "Saint Kitts and Nevis", phoneCode: "+1-869" },
  { abbreviation: "LC", label: "Saint Lucia", phoneCode: "+1-758" },
  { abbreviation: "PM", label: "Saint Pierre and Miquelon", phoneCode: "+508" },
  {
    abbreviation: "VC",
    label: "Saint Vincent and the Grenadines",
    phoneCode: "+1-784",
  },
  { abbreviation: "WS", label: "Samoa", phoneCode: "+685" },
  { abbreviation: "SM", label: "San Marino", phoneCode: "+378" },
  { abbreviation: "ST", label: "Sao Tome and Principe", phoneCode: "+239" },
  { abbreviation: "SA", label: "Saudi Arabia", phoneCode: "+966" },
  { abbreviation: "SN", label: "Senegal", phoneCode: "+221" },
  { abbreviation: "RS", label: "Serbia", phoneCode: "+381" },
  { abbreviation: "SC", label: "Seychelles", phoneCode: "+248" },
  { abbreviation: "SL", label: "Sierra Leone", phoneCode: "+232" },
  { abbreviation: "SG", label: "Singapore", phoneCode: "+65" },
  { abbreviation: "SK", label: "Slovakia", phoneCode: "+421" },
  { abbreviation: "SI", label: "Slovenia", phoneCode: "+386" },
  { abbreviation: "SB", label: "Solomon Islands", phoneCode: "+677" },
  { abbreviation: "SO", label: "Somalia", phoneCode: "+252" },
  { abbreviation: "ZA", label: "South Africa", phoneCode: "+27" },
  {
    abbreviation: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phoneCode: "",
  },
  { abbreviation: "ES", label: "Spain", phoneCode: "+34" },
  { abbreviation: "LK", label: "Sri Lanka", phoneCode: "+94" },
  { abbreviation: "SD", label: "Sudan", phoneCode: "+249" },
  { abbreviation: "SR", label: "Suriname", phoneCode: "+597" },
  { abbreviation: "SJ", label: "Svalbard and Jan Mayen", phoneCode: "+47" },
  { abbreviation: "SZ", label: "Swaziland", phoneCode: "+268" },
  { abbreviation: "SE", label: "Sweden", phoneCode: "+46" },
  { abbreviation: "CH", label: "Switzerland", phoneCode: "+41" },
  { abbreviation: "SY", label: "Syrian Arab Republic", phoneCode: "+963" },
  { abbreviation: "TW", label: "Taiwan, Province of China", phoneCode: "+886" },
  { abbreviation: "TJ", label: "Tajikistan", phoneCode: "+992" },
  {
    abbreviation: "TZ",
    label: "Tanzania, United Republic of",
    phoneCode: "+255",
  },
  { abbreviation: "TH", label: "Thailand", phoneCode: "+66" },
  { abbreviation: "TL", label: "Timor-Leste", phoneCode: "+670" },
  { abbreviation: "TG", label: "Togo", phoneCode: "+228" },
  { abbreviation: "TK", label: "Tokelau", phoneCode: "+690" },
  { abbreviation: "TO", label: "Tonga", phoneCode: "+676" },
  { abbreviation: "TT", label: "Trinidad and Tobago", phoneCode: "+1-868" },
  { abbreviation: "TN", label: "Tunisia", phoneCode: "+216" },
  { abbreviation: "TR", label: "Turkey", phoneCode: "+90" },
  { abbreviation: "TM", label: "Turkmenistan", phoneCode: "+993" },
  {
    abbreviation: "TC",
    label: "Turks and Caicos Islands",
    phoneCode: "+1-649",
  },
  { abbreviation: "TV", label: "Tuvalu", phoneCode: "+688" },
  { abbreviation: "UG", label: "Uganda", phoneCode: "+256" },
  { abbreviation: "UA", label: "Ukraine", phoneCode: "+380" },
  { abbreviation: "AE", label: "United Arab Emirates", phoneCode: "+971" },
  { abbreviation: "GB", label: "United Kingdom", phoneCode: "+44" },
  { abbreviation: "US", label: "United States", phoneCode: "+1" },
  { abbreviation: "UY", label: "Uruguay", phoneCode: "+598" },
  { abbreviation: "UZ", label: "Uzbekistan", phoneCode: "+998" },
  { abbreviation: "VU", label: "Vanuatu", phoneCode: "+678" },
  { abbreviation: "VE", label: "Venezuela", phoneCode: "+58" },
  { abbreviation: "VN", label: "Viet Nam", phoneCode: "+84" },
  { abbreviation: "VG", label: "Virgin Islands, British", phoneCode: "+1-284" },
  { abbreviation: "VI", label: "Virgin Islands, U.S.", phoneCode: "+1-340" },
  { abbreviation: "WF", label: "Wallis and Futuna", phoneCode: "+681" },
  { abbreviation: "EH", label: "Western Sahara", phoneCode: "+212" },
  { abbreviation: "YE", label: "Yemen", phoneCode: "+967" },
  { abbreviation: "ZM", label: "Zambia", phoneCode: "+260" },
  { abbreviation: "ZW", label: "Zimbabwe", phoneCode: "+263" },
];

export const STATES_DISTRICTS = [
  {
    state: "Andhra Pradesh",
    districts: [
      "Anantapur",
      "Chittoor",
      "East Godavari",
      "Guntur",
      "Krishna",
      "Kurnool",
      "Nellore",
      "Prakasam",
      "Srikakulam",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari",
      "YSR Kadapa",
    ],
  },
  {
    state: "Arunachal Pradesh",
    districts: [
      "Tawang",
      "West Kameng",
      "East Kameng",
      "Papum Pare",
      "Kurung Kumey",
      "Kra Daadi",
      "Lower Subansiri",
      "Upper Subansiri",
      "West Siang",
      "East Siang",
      "Siang",
      "Upper Siang",
      "Lower Siang",
      "Lower Dibang Valley",
      "Dibang Valley",
      "Anjaw",
      "Lohit",
      "Namsai",
      "Changlang",
      "Tirap",
      "Longding",
    ],
  },
  {
    state: "Assam",
    districts: [
      "Baksa",
      "Barpeta",
      "Biswanath",
      "Bongaigaon",
      "Cachar",
      "Charaideo",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Kamrup Metropolitan",
      "Kamrup",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Majuli",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "Dima Hasao",
      "Sivasagar",
      "Sonitpur",
      "South Salmara-Mankachar",
      "Tinsukia",
      "Udalguri",
      "West Karbi Anglong",
    ],
  },
  {
    state: "Bihar",
    districts: [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran (Motihari)",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur (Bhabua)",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger (Monghyr)",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia (Purnea)",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
    ],
  },
  {
    state: "Chandigarh (UT)",
    districts: ["Chandigarh"],
  },
  {
    state: "Chhattisgarh",
    districts: [
      "Balod",
      "Baloda Bazar",
      "Balrampur",
      "Bastar",
      "Bemetara",
      "Bijapur",
      "Bilaspur",
      "Dantewada (South Bastar)",
      "Dhamtari",
      "Durg",
      "Gariyaband",
      "Janjgir-Champa",
      "Jashpur",
      "Kabirdham (Kawardha)",
      "Kanker (North Bastar)",
      "Kondagaon",
      "Korba",
      "Korea (Koriya)",
      "Mahasamund",
      "Mungeli",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sukma",
      "Surajpur  ",
      "Surguja",
    ],
  },
  {
    state: "Dadra and Nagar Haveli (UT)",
    districts: ["Dadra & Nagar Haveli"],
  },
  {
    state: "Daman and Diu (UT)",
    districts: ["Daman", "Diu"],
  },
  {
    state: "Delhi (NCT)",
    districts: [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East  Delhi",
      "North West  Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West  Delhi",
      "West Delhi",
    ],
  },
  {
    state: "Goa",
    districts: ["North Goa", "South Goa"],
  },
  {
    state: "Gujarat",
    districts: [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Aravalli",
      "Banaskantha (Palanpur)",
      "Bharuch",
      "Bhavnagar",
      "Botad",
      "Chhota Udepur",
      "Dahod",
      "Dangs (Ahwa)",
      "Devbhoomi Dwarka",
      "Gandhinagar",
      "Gir Somnath",
      "Jamnagar",
      "Junagadh",
      "Kachchh",
      "Kheda (Nadiad)",
      "Mahisagar",
      "Mehsana",
      "Morbi",
      "Narmada (Rajpipla)",
      "Navsari",
      "Panchmahal (Godhra)",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha (Himmatnagar)",
      "Surat",
      "Surendranagar",
      "Tapi (Vyara)",
      "Vadodara",
      "Valsad",
    ],
  },
  {
    state: "Haryana",
    districts: [
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Mewat",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
    ],
  },
  {
    state: "Himachal Pradesh",
    districts: [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul &amp; Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur (Sirmour)",
      "Solan",
      "Una",
    ],
  },
  {
    state: "Jammu and Kashmir",
    districts: [
      "Anantnag",
      "Bandipore",
      "Baramulla",
      "Budgam",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kargil",
      "Kathua",
      "Kishtwar",
      "Kulgam",
      "Kupwara",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajouri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
    ],
  },
  {
    state: "Jharkhand",
    districts: [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribag",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela-Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
  },
  {
    state: "Karnataka",
    districts: [
      "Bagalkot",
      "Ballari (Bellary)",
      "Belagavi (Belgaum)",
      "Bengaluru (Bangalore) Rural",
      "Bengaluru (Bangalore) Urban",
      "Bidar",
      "Chamarajanagar",
      "Chikballapur",
      "Chikkamagaluru (Chikmagalur)",
      "Chitradurga",
      "Dakshina Kannada",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Hassan",
      "Haveri",
      "Kalaburagi (Gulbarga)",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru (Mysore)",
      "Raichur",
      "Ramanagara",
      "Shivamogga (Shimoga)",
      "Tumakuru (Tumkur)",
      "Udupi",
      "Uttara Kannada (Karwar)",
      "Vijayapura (Bijapur)",
      "Yadgir",
    ],
  },
  {
    state: "Kerala",
    districts: [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Thrissur",
      "Wayanad",
    ],
  },
  {
    state: "Lakshadweep (UT)",
    districts: [
      "Agatti",
      "Amini",
      "Androth",
      "Bithra",
      "Chethlath",
      "Kavaratti",
      "Kadmath",
      "Kalpeni",
      "Kilthan",
      "Minicoy",
    ],
  },
  {
    state: "Madhya Pradesh",
    districts: [
      "Agar Malwa",
      "Alirajpur",
      "Anuppur",
      "Ashoknagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
    ],
  },
  {
    state: "Maharashtra",
    districts: [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai Suburban",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  },
  {
    state: "Manipur",
    districts: [
      "Bishnupur",
      "Chandel",
      "Churachandpur",
      "Imphal East",
      "Imphal West",
      "Jiribam",
      "Kakching",
      "Kamjong",
      "Kangpokpi",
      "Noney",
      "Pherzawl",
      "Senapati",
      "Tamenglong",
      "Tengnoupal",
      "Thoubal",
      "Ukhrul",
    ],
  },
  {
    state: "Meghalaya",
    districts: [
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "North Garo Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "South West Garo Hills ",
      "South West Khasi Hills",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
    ],
  },
  {
    state: "Mizoram",
    districts: [
      "Aizawl",
      "Champhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Serchhip",
    ],
  },
  {
    state: "Nagaland",
    districts: [
      "Dimapur",
      "Kiphire",
      "Kohima",
      "Longleng",
      "Mokokchung",
      "Mon",
      "Peren",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunheboto",
    ],
  },
  {
    state: "Odisha",
    districts: [
      "Angul",
      "Balangir",
      "Balasore",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Deogarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghapur",
      "Jajpur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Kendujhar (Keonjhar)",
      "Khordha",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangpur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Sonepur",
      "Sundargarh",
    ],
  },
  {
    state: "Puducherry (UT)",
    districts: ["Karaikal", "Mahe", "Pondicherry", "Yanam"],
  },
  {
    state: "Punjab",
    districts: [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Ferozepur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Muktsar",
      "Nawanshahr (Shahid Bhagat Singh Nagar)",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Sahibzada Ajit Singh Nagar (Mohali)",
      "Sangrur",
      "Tarn Taran",
    ],
  },
  {
    state: "Rajasthan",
    districts: [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dholpur",
      "Dungarpur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Sri Ganganagar",
      "Tonk",
      "Udaipur",
    ],
  },
  {
    state: "Sikkim",
    districts: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  },
  {
    state: "Tamil Nadu",
    districts: [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Thanjavur",
      "Theni",
      "Thoothukudi (Tuticorin)",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tiruppur",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
  },
  {
    state: "Telangana",
    districts: [
      "Adilabad",
      "Bhadradri Kothagudem",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhoopalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Komaram Bheem Asifabad",
      "Mahabubabad",
      "Mahabubnagar",
      "Mancherial",
      "Medak",
      "Medchal",
      "Nagarkurnool",
      "Nalgonda",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Rangareddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal (Rural)",
      "Warangal (Urban)",
      "Yadadri Bhuvanagiri",
    ],
  },
  {
    state: "Tripura",
    districts: [
      "Dhalai",
      "Gomati",
      "Khowai",
      "North Tripura",
      "Sepahijala",
      "South Tripura",
      "Unakoti",
      "West Tripura",
    ],
  },
  {
    state: "Uttarakhand",
    districts: [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
    ],
  },
  {
    state: "Uttar Pradesh",
    districts: [
      "Agra",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Amethi (Chatrapati Sahuji Mahraj Nagar)",
      "Amroha (J.P. Nagar)",
      "Auraiya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur (Panchsheel Nagar)",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kanshiram Nagar (Kasganj)",
      "Kaushambi",
      "Kushinagar (Padrauna)",
      "Lakhimpur - Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "RaeBareli",
      "Rampur",
      "Saharanpur",
      "Sambhal (Bhim Nagar)",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamali (Prabuddh Nagar)",
      "Shravasti",
      "Siddharth Nagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  },
  {
    state: "West Bengal",
    districts: [
      "Alipurduar",
      "Bankura",
      "Birbhum",
      "Burdwan (Bardhaman)",
      "Cooch Behar",
      "Dakshin Dinajpur (South Dinajpur)",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Medinipur (West Medinipur)",
      "Purba Medinipur (East Medinipur)",
      "Purulia",
      "South 24 Parganas",
      "Uttar Dinajpur (North Dinajpur)",
    ],
  },
];
